export const DEFAULT_OPENAI_TRANSLATION_MODEL = 'gpt-4.1';
export const DEFAULT_OPENAI_TRANSLATION_TIMEOUT_MS = 60_000;
export const DEFAULT_OPENAI_GLOSSARY_MODEL = 'gpt-4.1';
export const DEFAULT_OPENAI_GLOSSARY_TIMEOUT_MS = 90_000;
export const DEFAULT_OPENAI_VIDEO_CREATIVE_MODEL = 'gpt-4.1';
export const DEFAULT_OPENAI_VIDEO_CREATIVE_TIMEOUT_MS = 90_000;
